### PR TITLE
Fix singular value in Period type #166

### LINKED ISSUE #166: Singular value in Period type is output in plural format
Examples:

- 1 week -> 1 weeks
- 1 month -> 1 months

To reproduce, type into any Period type field.

### PR DESCRIPTION
**Pull request by outkaj**

### CODE REVIEW

File: shared/src/main/scala/org/adridadou/openlaw/parser/template/variableTypes/PeriodType.scala [hunk 1]
```diff
@@ -145,10 +152,6 @@ class PeriodTypeParser(val input: ParserInput) extends Parser {
         }
       }).reduce((left, right) => left.plus(right)))
   }
-
-  def singularPlural(name:String):Rule0 = rule {
```
Comment (outkaj) [inline shared/src/main/scala/org/adridadou/openlaw/parser/template/variableTypes/PeriodType.scala]: (removed as this is not used anywhere)

**Comment by outkaj** [comment]
@craigwblake-openlaw it's a good point. It seems like the Period functionality is getting more complicated over time. We can open an issue
